import i18next from "i18next";
import ar from "./navigation-i18n/ar";
import en from "./navigation-i18n/en";
import tr from "./navigation-i18n/tr";

i18next.addResourceBundle("en", "navigation", en);
i18next.addResourceBundle("tr", "navigation", tr);
i18next.addResourceBundle("ar", "navigation", ar);

const navigationConfig = [
  {
    id: "applications",
    title: "",
    translate: "",
    type: "group",
    icon: "",
    children: [
      {
        id: "home",
        title: "Home",
        translate: "Home",
        type: "item",
        icon: "home",
        url: "/home",
      },
      {
        id: "OrganizationManagement",
        title: "Organizations",
        translate: "Organizations",
        type: "item",
        icon: "group",
        url: "/organization-management",
      },
      {
        id: "UserManagment",
        title: "User Management",
        translate: "User Management",
        type: "item",
        icon: "group",
        url: "/user-managment",
      },
      {
        id: "itemAnalysis",
        title: "Item Analysis",
        translate: "Item Analysis",
        type: "item",
        icon: "analytics",
        url: "#itemAnalysis",
      },
      {
        id: "authorSiteSettings",
        title: "Author Site Settings",
        translate: "Author Site Settings",
        type: "item",
        icon: "settings",
        url: "/author-site-settings",
      },
    ],
  },
  {
    id: "items",
    title: "items",
    translate: "items",
    type: "group",
    icon: "",
    children: [
      {
        id: "allitems",
        title: "All Items",
        translate: "All Items",
        type: "item",
        icon: "dvr",
        url: "#allitems",
      },
      {
        id: "createnewitem",
        title: "Create New Item",
        translate: "Create New Item",
        type: "item",
        icon: "subtitlesrounded",
        url: "/item-analysis",
      },
      {
        id: "itembulkupdates",
        title: "Bulk Updates",
        translate: "Bulk Updates",
        type: "item",
        icon: "subtitlesrounded",
        url: "#itembulkupdates",
      },
    ],
  },
  {
    id: "activities",
    title: "activities",
    translate: "activities",
    type: "group",
    icon: "",
    children: [
      {
        id: "allactivities",
        title: "All Activities",
        translate: "All Activities",
        type: "item",
        icon: "dvr",
        url: "#allactivities",
      },
      {
        id: "newactivity",
        title: "New Activity",
        translate: "New Activity",
        type: "item",
        icon: "subtitlesrounded",
        url: "#newactivity",
      },
      {
        id: "basetemplates",
        title: "Base Templates",
        translate: "Base Templates",
        type: "item",
        icon: "subtitlesrounded",
        url: "#basetemplates",
      },
      {
        id: "activitybulkupdates",
        title: "Bulk Updates",
        translate: "Bulk Updates",
        type: "item",
        icon: "subtitlesrounded",
        url: "/item-bank-details",
      },
    ],
  },
  {
    id: "tags",
    title: "tags",
    translate: "tags",
    type: "group",
    icon: "",
    children: [
      {
        id: "tagtypes",
        title: "Tag Types",
        translate: "Tag Types",
        type: "item",
        icon: "dvr",
        url: "#tagtypes",
      },
      {
        id: "taghierarchies",
        title: "Tag Hierarchies",
        translate: "Tag Hierarchies",
        type: "item",
        icon: "subtitlesrounded",
        url: "#taghierarchies",
      },
    ],
  },
  {
    id: "gradesub",
    title: "",
    translate: "",
    type: "group",
    icon: "",
    children: [
      {
        id: "grade",
        title: "Grade",
        translate: "Grade",
        type: "item",
        icon: "dvr",
        url: "#grade",
      },
      {
        id: "subject",
        title: "Subject",
        translate: "Subject",
        type: "item",
        icon: "subtitlesrounded",
        url: "#subject",
      },
    ],
  },
  {
    id: "insight",
    title: "insight",
    translate: "insight",
    type: "group",
    icon: "",
    children: [
      {
        id: "sessionDetails",
        title: "session details",
        translate: "session details",
        type: "item",
        icon: "dvr",
        url: "/session-details",
      },
      {
        id: "itemBankDetails",
        title: "Item Bank Details",
        translate: "Item Bank Details",
        type: "item",
        icon: "subtitlesrounded",
        url: "/item-bank-details",
      },
    ],
  },
  {
    id: "configuration",
    title: "configuration",
    translate: "configuration",
    type: "group",
    icon: "",
    children: [
      {
        id: "itemBanks",
        title: "Item Banks",
        translate: "Item Banks",
        type: "item",
        icon: "ballot",
        url: "/item-banks",
      },
      {
        id: "consumers",
        title: "Consumers",
        translate: "Consumers",
        type: "item",
        icon: "portrait",
        url: "/consumers",
      },
      {
        id: "custom",
        title: "Custom Questions",
        translate: "Custom Questions",
        type: "item",
        icon: "assignment",
        url: "/custom-questions",
      },
    ],
  },
  {
    id: "accountSettings",
    title: "",
    translate: "",
    type: "group",
    icon: "home",
    children: [
      {
        id: "myAccount",
        title: "My Account",
        translate: "My Account",
        type: "item",
        icon: "person",
        url: "/my-account",
      },
      {
        id: "settings",
        title: "Settings",
        translate: "Settings",
        type: "item",
        icon: "settingsapplicationssharp",
        url: "/settings",
      },
      {
        id: "logout",
        title: "Logout",
        translate: "Logout",
        type: "item",
        icon: "input",
        url: "/logout",
      },
    ],
  },
];

export default navigationConfig;
